import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import MainPage from "../components/landingpage/MainPage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Porsche-Mini-Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 className="dark:text-red-400 text-3xl uppercase">test</h2>
        <MainPage />
      </main>
    </>
  );
}
