import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import LandingPage from "../components/LandingPage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Porsche-Mini-Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="py-10 mb-10 text-center bg-slate-600">
          NAV PLACEHOLDER
        </nav>
        <LandingPage />
      </main>
    </>
  );
}
